name: ena
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - icu=75.1
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.3
  - pip=25.2
  - python=3.10.18
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - lftp
  - pip:
      - beautifulsoup4==4.13.5
      - et-xmlfile==2.0.0
      - numpy==2.2.6
      - openpyxl==3.1.5
      - pandas==2.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - soupsieve==2.8
      - typing-extensions==4.15.0
      - tzdata==2025.2
